name: Default

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Provision infrastructure
      uses: azure/arm-deploy@v1
      id: deploy
      with:
        resourceGroupName: lookup
        template: .azure/main.bicep
        parameters: sqlAdministratorLoginPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
    
    - name: Get ACR access token
      uses: Azure/CLI@v1
      id: acr
      with:
        inlineScript: |
          output=`az acr login -n ${{ steps.deploy.outputs.registryName }} --expose-token`
          echo "::set-output name=accessToken::`echo $output | jq -r '.accessToken'`"
          echo "::set-output name=loginServer::`echo $output | jq -r '.loginServer'`"

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ steps.acr.outputs.loginServer }}
        username: 00000000-0000-0000-0000-000000000000
        password: ${{ steps.acr.outputs.accessToken }}
    
    - name: Get application version
      id: version
      run: |
        echo "::set-output name=version::`cat version`"

    - name: Build container image
      run: |
        docker build -t ${{ steps.deploy.outputs.imageName }}:${{ steps.version.outputs.version }} -o type=docker .
    
    - name: Scan container image
      uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: ${{ steps.deploy.outputs.imageName }}:${{ steps.version.outputs.version }}
    
    - name: Push container image
      run: |
        docker push ${{ steps.deploy.outputs.imageName }}:${{ steps.version.outputs.version }}

    - name: Deploy app
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: lookup
        template: .azure/app.bicep
        parameters: app=${{ steps.deploy.outputs.siteName }} image=${{ steps.deploy.outputs.imageName }}:${{ steps.version.outputs.version }}
